### ISSUE TITLE
logging configs with custom Python function filters crashes dynamic-logging

### ISSUE THREAD

**Issue by abulka** [Yupeek/django-dynamic-logging#6]
Filters with custom filter functions don't seem to be handled and crash in /dynamic_logging/models.py

    module_logger.debug("applying config %s", json.dumps(config))

My custom `skip_static_requests` function is not JSON serializable, hence the crash.

    def skip_static_requests(record):
        if record.args[0].startswith('GET /static/'):  # filter whatever you want
            return False
        return True

Notice the filter in:

    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'filters': {
            # use Django's built in CallbackFilter to point to your filter
            'skip_static_requests': {
                '()': 'django.utils.log.CallbackFilter',
                'callback': skip_static_requests
            }
        },
        'formatters': {
            # django's default formatter
            'django.server': {
                '()': 'django.utils.log.ServerFormatter',
                'format': '[%(server_time)s] %(message)s',
            },
        },
        'handlers': {
            # django's default handler...
            'django.server': {
                'level': 'INFO',
                'filters': ['skip_static_requests'],
                'class': 'logging.StreamHandler',
                'formatter': 'django.server',
            },
        },
        'loggers': {
            # django's default logger
            'django.server': {
                'handlers': ['django.server'],
                'level': 'INFO',
                'propagate': False,
            },
        }
    }

**Comment by ornoone** [comment]
fixed in next release 2.0
