### ISSUE TITLE
Installation documentation typo in name of app

### ISSUE THREAD

**Issue by abulka** [Yupeek/django-dynamic-logging#7]
The advice to

    add dynamic-logging to your INSTALLED_APPS

should be

    add 'dynamic_logging' to your INSTALLED_APPS

so that's an underscore not a dash, and of course quotes.

viz.

     'django.contrib.staticfiles',
     'django_extensions',
     'django.contrib.sites',
     ...
     'dynamic_logging',
     ...

**Comment by ornoone** [comment]
thanks for your help, and sorry for the delay.
